version: '3.9'

services:
  mysql:
    build:
      context: ./mysql
    container_name: mysql_localhost
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - TZ="Asia/Jakarta"
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./storage/mysql:/var/lib/mysql:rw

  mongodb:
    build:
      context: ./mongodb
    container_name: mongo_localhost
    ports:
      - ${MONGODB_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ./storage/mongodb:/data/db

  elasticsearch:
    build:
      context: ./elasticsearch
    container_name: elasticsearch_localhost
    ports:
      - ${ELASTICSEARCH_PORT_1}:9200
      - ${ELASTICSEARCH_PORT_2}:9300
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ./storage/elasticsearch:/var/lib/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
